remove docs test

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -64,30 +64,31 @@ jobs:
 
       - run: pnpm package
 
-  test-doc:
-    runs-on: ubuntu-latest
+  # Hyperlink will contain commit hash which means it will always fail
+  # test-doc:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: pnpm/action-setup@v4
+  #     - uses: pnpm/action-setup@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
-          cache: 'pnpm'
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20.x'
+  #         cache: 'pnpm'
 
-      - run: corepack enable
+  #     - run: corepack enable
       
-      - run: pnpm install --ignore-scripts
+  #     - run: pnpm install --ignore-scripts
 
-      - name: Generate documentation
-        run: pnpm packages:generate-docs
+  #     - name: Generate documentation
+  #       run: pnpm packages:generate-docs
   
-      - name: Check for uncommitted changes in docs
-        run: |
-          git add .
-          if ! git diff --cached --exit-code; then
-            echo "Documentation is outdated. Please run 'pnpm packages:generate-docs' and commit the changes."
-            exit 1
-          fi
+  #     - name: Check for uncommitted changes in docs
+  #       run: |
+  #         git add .
+  #         if ! git diff --cached --exit-code; then
+  #           echo "Documentation is outdated. Please run 'pnpm packages:generate-docs' and commit the changes."
+  #           exit 1
+  #         fi
